name: 'dbt_project'
version: '1.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
