version: 2

sources:
  - name: raw
    tables:
      - name: yellow_tripdata_raw
      - name: taxi_zone_lookup

models:
  - name: stg_trips
    tests:
      - not_null:
          column_name: pickup_loc_id
      - relationships:
          column_name: pickup_loc_id
          to: source('raw', 'taxi_zone_lookup')
          field: location_id

  - name: dim_locations
    tests:
      - unique:
          column_name: location_id
      - not_null:
          column_name: location_id

  - name: dim_time
    tests:
      - unique:
          column_name: time_id
      - not_null:
          column_name: time_id

  - name: fact_trips
    tests:
      - not_null:
          column_name: trip_id
